from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select, func, desc
from sqlalchemy.ext.asyncio import AsyncSession
from tokenfinops.models.base import get_db
from tokenfinops.models.usage import UsageRecord
from tokenfinops.models.budget import Budget, BudgetUsage
from tokenfinops.models.recommendation import DBRecommendation
from tokenfinops.providers.registry import provider_registry

router = APIRouter()

@router.get("/overview")
async def get_overview(db: AsyncSession = Depends(get_db)):
    """Retrieve high-level KPIs for the metrics dashboard."""
    try:
        # Sum total actual costs, count cache hits, average latency
        stmt = select(
            func.count(UsageRecord.id),
            func.count(UsageRecord.id).filter(UsageRecord.cache_hit == True),
            func.sum(UsageRecord.actual_cost),
            func.avg(UsageRecord.latency_ms),
            func.sum(UsageRecord.tokens_saved)
        )
        res = await db.execute(stmt)
        total_calls, cache_hits, total_spent, avg_latency, tokens_saved = res.fetchone() or (0, 0, 0.0, 0.0, 0)

        cache_rate = cache_hits / total_calls if total_calls > 0 else 0.0
        
        # Calculate estimated savings (actual cost if we did not cache or route)
        # Using a conservative calculation
        estimated_savings = float(tokens_saved or 0) * 0.000015  # standard $0.015 per 1k tokens proxy savings

        return {
            "total_calls": total_calls,
            "cache_hit_rate": cache_rate,
            "total_spent": float(total_spent or 0.0),
            "avg_latency_ms": float(avg_latency or 0.0),
            "estimated_savings": estimated_savings,
            "active_providers": len(provider_registry.list_active_providers())
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/spend")
async def get_spend_series(db: AsyncSession = Depends(get_db)):
    """Retrieve daily cost aggregate values for time series chart rendering."""
    try:
        stmt = select(
            func.date_trunc('day', UsageRecord.timestamp).label('day'),
            func.sum(UsageRecord.actual_cost).label('spent')
        ).group_by('day').order_by('day')
        
        res = await db.execute(stmt)
        rows = res.fetchall()
        
        series = []
        for r in rows:
            day_str = r.day.strftime("%Y-%m-%d") if r.day else "unknown"
            series.append({
                "date": day_str,
                "spent": float(r.spent or 0.0)
            })
        return series
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/models")
async def get_model_breakdown(db: AsyncSession = Depends(get_db)):
    """Retrieve spend totals grouped by model."""
    try:
        stmt = select(
            UsageRecord.routed_model,
            func.sum(UsageRecord.actual_cost).label('spent'),
            func.count(UsageRecord.id).label('calls')
        ).group_by(UsageRecord.routed_model)
        
        res = await db.execute(stmt)
        rows = res.fetchall()
        
        breakdown = []
        for r in rows:
            breakdown.append({
                "model": r.routed_model or "unknown",
                "spent": float(r.spent or 0.0),
                "calls": r.calls
            })
        return breakdown
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/teams")
async def get_teams_budgets(db: AsyncSession = Depends(get_db)):
    """Retrieve details on current team allocations and budget tracking stats."""
    try:
        stmt = select(Budget)
        res = await db.execute(stmt)
        budgets = res.scalars().all()
        
        team_data = []
        for b in budgets:
            # Query recent usage
            stmt_usage = select(BudgetUsage).where(BudgetUsage.budget_id == b.id).order_by(desc(BudgetUsage.period_start))
            res_usage = await db.execute(stmt_usage)
            latest_usage = res_usage.scalars().first()
            
            spent = float(latest_usage.spent) if latest_usage else 0.0
            team_data.append({
                "team_id": b.team_id,
                "period": b.period,
                "amount": float(b.amount),
                "spent": spent,
                "utilization_pct": (spent / float(b.amount) * 100.0) if float(b.amount) > 0 else 0.0,
                "downgrade_model": b.downgrade_model
            })
        return team_data
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/recommendations")
async def get_recommendations(db: AsyncSession = Depends(get_db)):
    """List active optimization suggestions generated by the analysis scheduler."""
    try:
        stmt = select(DBRecommendation).where(DBRecommendation.status == "active").order_by(desc(DBRecommendation.created_at))
        res = await db.execute(stmt)
        return res.scalars().all()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/requests")
async def get_recent_requests(limit: int = 50, db: AsyncSession = Depends(get_db)):
    """Fetch recent model completion transaction logs."""
    try:
        stmt = select(UsageRecord).order_by(desc(UsageRecord.timestamp)).limit(limit)
        res = await db.execute(stmt)
        records = res.scalars().all()
        
        formatted = []
        for r in records:
            formatted.append({
                "id": str(r.id),
                "timestamp": r.timestamp.isoformat() if r.timestamp else None,
                "requested_model": r.requested_model,
                "routed_model": r.routed_model,
                "provider": r.provider,
                "input_tokens": r.input_tokens,
                "output_tokens": r.output_tokens,
                "cost": float(r.actual_cost),
                "latency_ms": r.latency_ms,
                "cache_hit": r.cache_hit,
                "status": r.status
            })
        return formatted
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
