apiVersion: v1
kind: Service
metadata:
  name: tokenfinops-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: tokenfinops
