import os
import shutil
import sys
from pathlib import Path

def print_banner():
    print("=" * 60)
    print("         TokenFinOps Setup Wizard (BYOK Open Platform)        ")
    print("=" * 60)
    print("This wizard will help you configure your .env and config.yaml files.")
    print("Leave values blank if you do not want to configure a provider.\n")

def check_existing_config() -> bool:
    env_path = Path(".env")
    yaml_path = Path("config.yaml")
    if env_path.exists() or yaml_path.exists():
        resp = input("Configuration files (.env or config.yaml) already exist. Overwrite? (y/N): ").strip().lower()
        return resp == "y"
    return True

def run_wizard():
    print_banner()
    if not check_existing_config():
        print("Setup cancelled. Existing configuration preserved.")
        sys.exit(0)

    env_variables = {}

    # 1. Database & Cache Defaults
    print("--- Database & Redis Configuration ---")
    db_url = input("PostgreSQL Connection URL (default: postgresql://tokenfinops:tokenfinops@localhost:5432/tokenfinops): ").strip()
    env_variables["DATABASE_URL"] = db_url if db_url else "postgresql://tokenfinops:tokenfinops@localhost:5432/tokenfinops"

    redis_url = input("Redis Connection URL (default: redis://localhost:6379/0): ").strip()
    env_variables["REDIS_URL"] = redis_url if redis_url else "redis://localhost:6379/0"
    print()

    # 2. LLM Provider API Keys
    print("--- LLM Provider Configurations (Optional) ---")
    openai_key = input("Enter OpenAI API Key (sk-...): ").strip()
    if openai_key:
        env_variables["OPENAI_API_KEY"] = openai_key
        openai_base = input("Custom OpenAI Base URL (e.g. for Azure/Proxy, default: blank): ").strip()
        if openai_base:
            env_variables["OPENAI_BASE_URL"] = openai_base

    anthropic_key = input("Enter Anthropic API Key (sk-ant-...): ").strip()
    if anthropic_key:
        env_variables["ANTHROPIC_API_KEY"] = anthropic_key

    gemini_key = input("Enter Google Gemini API Key (AIza...): ").strip()
    if gemini_key:
        env_variables["GEMINI_API_KEY"] = gemini_key

    openrouter_key = input("Enter OpenRouter API Key: ").strip()
    if openrouter_key:
        env_variables["OPENROUTER_API_KEY"] = openrouter_key

    ollama_url = input("Ollama Base URL (default: http://localhost:11434): ").strip()
    env_variables["OLLAMA_BASE_URL"] = ollama_url if ollama_url else "http://localhost:11434"

    vllm_url = input("vLLM Base URL (default: blank): ").strip()
    if vllm_url:
        env_variables["VLLM_BASE_URL"] = vllm_url
    print()

    # 3. Embedding Configurations
    print("--- Pluggable Embedding Configuration ---")
    print("Choose embedding provider for Semantic Cache:")
    print("1) sentence-transformers (local, free, default)")
    print("2) openai (cloud, paid)")
    print("3) ollama (local, free)")
    print("4) cohere (cloud, paid)")
    
    choice = input("Select embedding provider (1-4, default: 1): ").strip()
    
    if choice == "2":
        env_variables["EMBEDDING_PROVIDER"] = "openai"
        model = input("OpenAI Embedding Model (default: text-embedding-3-small): ").strip()
        env_variables["EMBEDDING_MODEL"] = model if model else "text-embedding-3-small"
    elif choice == "3":
        env_variables["EMBEDDING_PROVIDER"] = "ollama"
        model = input("Ollama Embedding Model (default: nomic-embed-text): ").strip()
        env_variables["EMBEDDING_MODEL"] = model if model else "nomic-embed-text"
    elif choice == "4":
        env_variables["EMBEDDING_PROVIDER"] = "cohere"
        model = input("Cohere Embedding Model (default: embed-english-v3.0): ").strip()
        env_variables["EMBEDDING_MODEL"] = model if model else "embed-english-v3.0"
        cohere_key = input("Enter Cohere API Key (or set COHERE_API_KEY in env): ").strip()
        if cohere_key:
            env_variables["COHERE_API_KEY"] = cohere_key
    else:
        env_variables["EMBEDDING_PROVIDER"] = "sentence-transformers"
        model = input("SentenceTransformers Model (default: all-MiniLM-L6-v2): ").strip()
        env_variables["EMBEDDING_MODEL"] = model if model else "all-MiniLM-L6-v2"
    print()

    # 4. Generate .env file
    print("Writing .env file...")
    try:
        with open(".env", "w", encoding="utf-8") as f:
            f.write("# Generated by TokenFinOps Setup Wizard\n")
            for k, v in env_variables.items():
                f.write(f"{k}={v}\n")
        print("✓ Created .env successfully.")
    except Exception as e:
        print(f"✗ Failed to write .env file: {e}")

    # 5. Create config.yaml from config.yaml.example if it doesn't exist
    yaml_path = Path("config.yaml")
    example_path = Path("config.yaml.example")
    
    if example_path.exists() and not yaml_path.exists():
        print("Creating config.yaml from template...")
        try:
            shutil.copy(example_path, yaml_path)
            print("✓ Created config.yaml successfully.")
        except Exception as e:
            print(f"✗ Failed to create config.yaml: {e}")
    elif yaml_path.exists():
        print("config.yaml already exists. Skipping copy.")
    else:
        print("config.yaml.example template not found. Skipping config.yaml creation.")

    print("\n" + "=" * 60)
    print("Setup Complete! You can now start TokenFinOps.")
    print("Run your server using: uvicorn tokenfinops.main:app --reload")
    print("=" * 60)

if __name__ == "__main__":
    run_wizard()
